# Generated by Django 5.1.7 on 2025-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
