# Generated by Django 5.1.7 on 2025-03-31 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveBigIntegerField()),
                ('category', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('roupa_feminina', 'Roupa Feminina'), ('roupa_masculina', 'Roupa Masculina'), ('roupa_infantil', 'Roupa Infantil'), ('imoveis', 'Imóveis'), ('outro', 'Outro')], max_length=50)),
                ('photo', models.ImageField(upload_to='pedidos/')),
                ('content', models.TextField()),
                ('date_product', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
