# Generated by Django 5.1.7 on 2025-03-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recebidorform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoform',
            options={'ordering': ['-date_product']},
        ),
    ]
