# Generated by Django 5.1.7 on 2025-03-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantidade', models.PositiveBigIntegerField()),
                ('category', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('roupa_feminina', 'Roupa Feminina'), ('roupa_masculina', 'Roupa Masculina'), ('roupa_infantil', 'Roupa Infantil'), ('imoveis', 'Imóveis'), ('outro', 'Outro')], max_length=50)),
                ('photo', models.ImageField(upload_to='produtos/')),
            ],
        ),
    ]
