# Generated by Django 5.1.7 on 2025-03-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doadorform', '0002_productd_author_productd_date_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productd',
            old_name='quantidade',
            new_name='quantity',
        ),
    ]
