# Generated by Django 5.1.7 on 2025-03-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doadorform', '0004_productd_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productd',
            options={'ordering': ['-date_product']},
        ),
    ]
